### ISSUE TITLE
Publish 4.0.0 to npm?

### ISSUE THREAD

**Issue by devongovett** [jonathantneal/postcss-logical#16]
Looks like 4.0.0 was tagged today, but is not published to npm.

**Comment by jonathantneal** [comment]
I am not ready to publish it, because caniuse data is incorrect. This is a hard problem, and I don’t want to publish something misleading.

https://caniuse.com/#feat=css-logical-props

This caniuse page suggests the Logical Properties working draft is fully implemented in a few browsers. However, the Logical Properties spec is only partially implemented in any browser, with differing features implemented in different browsers across different versions.

If I separated this plugin into pieces grouped by browser implementations (e.g. offset side as one plugin, added in Chrome 69 + Firefox 63, and then logical size as another plugin, added in Chrome 57, Firefox 41, Safari 12.1, and Safari iOS 12.2), I would need to split this plugin at least 7 times. And even then, I would have to create and have merged another half dozen entries into caniuse. And what if some of the implementations have bugs? For example, it seems like border-radius is not implemented correctly in Firefox. Oh boy.

**Comment by devongovett** [comment]
hmm, I'm probably missing something, but where does postcss-logical use caniuse data? My understanding was that it just transforms everything. Using caniuse data to transform only some of the properties does seem like a nice future feature though, but I'm unclear why that would be a blocker for this release and not a future one.

**Comment by jonathantneal** [comment]
Yes, you are right. It just means I will probably release another new major very soon.

I am wearing a lot of hats and so I do struggle to know when a problem is a blocker for this project versus another.

**Comment by jonathantneal** [comment]
Right now, there is no way for you to enable or disable specific transforms within PostCSS Logical, even though most modern browsers implement portions of the transforms performed by this plugin.

If I do not allow granular adoption of real, native logical properties and values, then I’m hurting your upgrade path, and limiting your ability to find & fix bugs before your browserslist turns the whole plugin off. Those bugs could be with this project, with a browser, or with the spec itself, so the damage is potentially far reaching.

Also, this project is used by PostCSS Preset Env, which uses caniuse to determine whether this plugin should run. Right now, there are false greens that would cause this plugin not to run, meaning some folks would never get transforms for features their browser does not support.

Like you said, though, that doesn’t block me from releasing some valuable fixes to this project right now. I will do that and let you know when it is published.

In the future, I think every PostCSS plugin should individually expose its own ids for caniuse, cssdb, mdn-browser-compat, w3c, etc. so that configuration and tooling determine the granularity of transforms.

**Comment by jonathantneal** [comment]
v4 is published. :tada: Thanks for talking with me about this.

**Comment by devongovett** [comment]
Awesome, thanks so much. I agree with everything you said above too btw. 👍
