### ISSUE TITLE
Pipe fallback CSS rules to separate file

### ISSUE THREAD

**Issue by distantnative** [jonathantneal/postcss-logical#36]
Is there any way with your plugin to not add the RTL fallback selectors to the original CSS but instead pipe them into a separate file? So only to transform the LTR selectors, but have the RTL fallback selectors (the ones with `:dir()`) in another file.

Use case: we would like to load that file only when the interface is in a RTL language.

Thanks for the plugin!

**Comment by romainmenke** [comment]
@distantnative this repo has move to [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins). Because github locks all code, issues and pr's for archived repositories further discussion here will no longer be possible :/

If need you can [start a discussion here](https://github.com/csstools/postcss-plugins/discussions/categories/q-a)

-------

Although this would be a really great feature, it would be tricky to generalise in a way that it works for most users.

Most tooling assumes either a bundler or a one to one relation between inputs and outputs.
Extracting part of the source CSS introduces these issues :

- what is the output dir
- what is the output file name
- PostCSS 8 doesn't run plugins sequentially -> have all transforms been applied before extraction?
- how does it affect sourcemaps?

I wanted something similar to split by `@supports` and `@media` :
https://github.com/romainmenke/postcss-split-by-media

Creating a dedicated plugin that works for your stack and setup based on the example above might be doable?

**Comment by romainmenke** [comment]
@distantnative It is possible to use the `dir` plugin option to only get CSS for either `ltr` or `rtl`. Running postcss twice (once for each value) produces two files.

You can then use any method to load either file.
